export interface ResumePlaceholder {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'date' | 'email' | 'phone' | 'url' | 'select' | 'list';
  section: string;
  required: boolean;
  aiEnhanceable: boolean;
  placeholder?: string;
  validation?: {
    pattern?: string;
    minLength?: number;
    maxLength?: number;
  };
  aliases?: string[];
  suggestions?: string[];
}

export const RESUME_PLACEHOLDERS: ResumePlaceholder[] = [
  {
    key: 'full_name',
    label: 'Full Name',
    type: 'text',
    section: 'personal',
    required: true,
    aiEnhanceable: false,
    placeholder: 'John Doe',
    aliases: ['name', 'candidate_name', 'fullname'],
    suggestions: ['nam'],
  },
  {
    key: 'phone',
    label: 'Phone',
    type: 'phone',
    section: 'personal',
    required: true,
    aiEnhanceable: false,
    placeholder: '+91-9876543210',
    aliases: ['phone_number', 'mobile', 'contact'],
    suggestions: ['ph', 'mob'],
  },
  {
    key: 'email',
    label: 'Email',
    type: 'email',
    section: 'personal',
    required: true,
    aiEnhanceable: false,
    placeholder: 'john@example.com',
    aliases: ['email_id', 'mail'],
    suggestions: ['e_mail'],
  },
  {
    key: 'github',
    label: 'GitHub',
    type: 'url',
    section: 'personal',
    required: false,
    aiEnhanceable: false,
    placeholder: 'github.com/johndoe',
    aliases: ['github_url', 'github_username'],
    suggestions: ['git', 'githb'],
  },
  {
    key: 'linkedin',
    label: 'LinkedIn',
    type: 'url',
    section: 'personal',
    required: false,
    aiEnhanceable: false,
    placeholder: 'linkedin.com/in/johndoe',
    aliases: ['linkedin_url', 'linked_in'],
    suggestions: ['linked', 'linkdin'],
  },
  {
    key: 'website',
    label: 'Website',
    type: 'url',
    section: 'personal',
    required: false,
    aiEnhanceable: false,
    placeholder: 'johndoe.dev',
    aliases: ['portfolio', 'personal_website'],
    suggestions: ['site', 'web'],
  },
  {
    key: 'location',
    label: 'Location',
    type: 'text',
    section: 'personal',
    required: false,
    aiEnhanceable: false,
    placeholder: 'New Delhi, India',
    aliases: ['city', 'address'],
    suggestions: ['loc'],
  },
  {
    key: 'professional_summary',
    label: 'Professional Summary',
    type: 'textarea',
    section: 'summary',
    required: true,
    aiEnhanceable: true,
    placeholder: 'Brief professional objective...',
    aliases: ['about_me', 'profile', 'objective'],
    suggestions: ['summry', 'abt', 'prof'],
  },
  {
    key: 'skills',
    label: 'Skills',
    type: 'list',
    section: 'skills',
    required: true,
    aiEnhanceable: false,
    placeholder: 'Java, Spring Boot, MongoDB...',
    aliases: ['technical_skills', 'skills_list', 'core_skills'],
    suggestions: ['skill', 'skiils', 'skilss'],
  },
  {
    key: 'experience_company',
    label: 'Company',
    type: 'text',
    section: 'experience',
    required: true,
    aiEnhanceable: false,
    placeholder: 'OpenAI',
    aliases: ['company', 'company_name', 'employer'],
    suggestions: ['compny', 'comp'],
  },
  {
    key: 'experience_role',
    label: 'Role',
    type: 'text',
    section: 'experience',
    required: true,
    aiEnhanceable: false,
    placeholder: 'Backend Engineer',
    aliases: ['role', 'job_title', 'position'],
    suggestions: ['roll', 'roel', 'positon'],
  },
  {
    key: 'experience_start_date',
    label: 'Start Date',
    type: 'date',
    section: 'experience',
    required: false,
    aiEnhanceable: false,
    placeholder: '2023-06',
    aliases: ['start_date', 'from_date', 'experience_start'],
    suggestions: ['start'],
  },
  {
    key: 'experience_end_date',
    label: 'End Date',
    type: 'date',
    section: 'experience',
    required: false,
    aiEnhanceable: false,
    placeholder: '2023-12',
    aliases: ['end_date', 'to_date', 'experience_end'],
    suggestions: ['end'],
  },
  {
    key: 'experience_description',
    label: 'Experience Description',
    type: 'textarea',
    section: 'experience',
    required: false,
    aiEnhanceable: true,
    placeholder: 'Describe your responsibilities and achievements...',
    aliases: ['description', 'responsibilities', 'duties', 'experience_details'],
    suggestions: ['responsibilty', 'text'],
  },
  {
    key: 'experience_technologies',
    label: 'Technologies Used',
    type: 'text',
    section: 'experience',
    required: false,
    aiEnhanceable: false,
    placeholder: 'Java, Spring Boot, PostgreSQL',
    aliases: ['technologies', 'tech_stack', 'tools'],
    suggestions: ['tech'],
  },
  {
    key: 'education_degree',
    label: 'Degree',
    type: 'text',
    section: 'education',
    required: true,
    aiEnhanceable: false,
    placeholder: 'B.Tech CSE',
    aliases: ['degree', 'qualification', 'course'],
    suggestions: ['degre'],
  },
  {
    key: 'education_institution',
    label: 'Institution',
    type: 'text',
    section: 'education',
    required: true,
    aiEnhanceable: false,
    placeholder: 'Sharda University',
    aliases: ['institution', 'school', 'college', 'university'],
    suggestions: ['inst', 'insitution'],
  },
  {
    key: 'education_start_year',
    label: 'Start Year',
    type: 'date',
    section: 'education',
    required: false,
    aiEnhanceable: false,
    placeholder: '2023',
    aliases: ['start_year', 'from_year'],
    suggestions: ['start'],
  },
  {
    key: 'education_end_year',
    label: 'End Year',
    type: 'date',
    section: 'education',
    required: false,
    aiEnhanceable: false,
    placeholder: '2027',
    aliases: ['end_year', 'to_year', 'graduation_year', 'yop'],
    suggestions: ['yer', 'yr', 'year'],
  },
  {
    key: 'education_cgpa',
    label: 'CGPA/GPA',
    type: 'text',
    section: 'education',
    required: false,
    aiEnhanceable: false,
    placeholder: '8.5 / 10',
    aliases: ['cgpa', 'gpa', 'cgpa_score'],
    suggestions: ['cgpa_score'],
  },
  {
    key: 'education_details',
    label: 'Education Details',
    type: 'textarea',
    section: 'education',
    required: false,
    aiEnhanceable: true,
    placeholder: 'Additional education details...',
    aliases: ['details', 'education_description'],
    suggestions: ['text'],
  },
  {
    key: 'project_name',
    label: 'Project Name',
    type: 'text',
    section: 'projects',
    required: true,
    aiEnhanceable: false,
    placeholder: 'Academic Universe',
    aliases: ['project_name', 'proj_name'],
    suggestions: ['proj_name'],
  },
  {
    key: 'project_description',
    label: 'Project Description',
    type: 'textarea',
    section: 'projects',
    required: false,
    aiEnhanceable: true,
    placeholder: 'Describe the project...',
    aliases: ['description', 'project_desc', 'details'],
    suggestions: ['descr', 'text'],
  },
  {
    key: 'project_technologies',
    label: 'Technologies Used',
    type: 'text',
    section: 'projects',
    required: false,
    aiEnhanceable: false,
    placeholder: 'React, Node.js, MongoDB',
    aliases: ['technologies', 'tech_stack', 'tools'],
    suggestions: ['tech'],
  },
  {
    key: 'project_url',
    label: 'Project URL',
    type: 'url',
    section: 'projects',
    required: false,
    aiEnhanceable: false,
    placeholder: 'github.com/academic-universe',
    aliases: ['url', 'link', 'demo_url'],
    suggestions: ['link'],
  },
  {
    key: 'certification_name',
    label: 'Certification Name',
    type: 'text',
    section: 'certifications',
    required: true,
    aiEnhanceable: false,
    placeholder: 'AWS Certified Developer',
    aliases: ['cert_name', 'certification'],
    suggestions: ['cert'],
  },
  {
    key: 'certification_issuer',
    label: 'Issuer',
    type: 'text',
    section: 'certifications',
    required: false,
    aiEnhanceable: false,
    placeholder: 'Amazon',
    aliases: ['issuer', 'issuing_body', 'authority'],
    suggestions: ['issusr'],
  },
  {
    key: 'certification_issue_date',
    label: 'Issue Date',
    type: 'date',
    section: 'certifications',
    required: false,
    aiEnhanceable: false,
    placeholder: '2024-01',
    aliases: ['issue_date', 'cert_date', 'date'],
    suggestions: ['dt'],
  },
  {
    key: 'certification_expiry_date',
    label: 'Expiry Date',
    type: 'date',
    section: 'certifications',
    required: false,
    aiEnhanceable: false,
    placeholder: '2027-01',
    aliases: ['expiry_date', 'valid_until'],
    suggestions: ['exp'],
  },
  {
    key: 'certification_details',
    label: 'Certification Details',
    type: 'textarea',
    section: 'certifications',
    required: false,
    aiEnhanceable: true,
    placeholder: 'Additional certification details...',
    aliases: ['details', 'certification_description'],
    suggestions: ['text'],
  },
  {
    key: 'additional_information',
    label: 'Additional Information',
    type: 'textarea',
    section: 'additional',
    required: false,
    aiEnhanceable: false,
    placeholder: 'Any extra information...',
    aliases: ['additional_info', 'extra_info', 'other'],
    suggestions: ['add', 'extra'],
  },
];

export const DEPRECATED_PLACEHOLDERS = new Set([
  'text',
  'items',
  'value',
  'content',
  'data',
  'description',
  'responsibilities',
]);

export const SECTION_ORDER: Record<string, number> = {
  personal: 0,
  summary: 1,
  skills: 2,
  experience: 3,
  education: 4,
  projects: 5,
  certifications: 6,
  additional: 7,
};

export const SECTION_LABELS: Record<string, string> = {
  personal: 'Personal Information',
  summary: 'Professional Summary',
  skills: 'Skills',
  experience: 'Experience',
  education: 'Education',
  projects: 'Projects',
  certifications: 'Certifications',
  additional: 'Additional Information',
};
